name: Hybrid Config Analysis

on:
  pull_request:
    branches:
      - 'main'
    #paths:
    #  - '/gitops/**'

jobs:
  analyze-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tca
          clean: true
      
      - name: Validate Istio Configs
        uses: ./tca
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }}
          mesh-config: |-
            gitops/bookinfo/bookinfo-gateway.yaml
            gitops/bookinfo/bookinfo.yaml
          local-only: true
          #kube-config: ${{ secrets.KUBECONFIG }}
          #github-token: ${{ secrets.GH_PAT }}
      
      - name: Validation failure
        uses: ./tca
        continue-on-error: true # Continue even if the job fails
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }}
          mesh-config: |-
            ./tca/test/manifest.yaml
            ./tca/test/failed.yaml
          github-token: ${{ secrets.GH_PAT }}
          local-only: true
