name: Hybrid Config Analysis

on:
  pull_request:
    paths:
      - 'istio/**'

jobs:
  analyze-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Istio Configs
        uses: tetratelabs/tca-action@main
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }
          mesh-config: |-
            ./istio/gateway.yaml
            ./istio/virtualservice.yaml
            test/failed.yaml
          kube-config: ${{ secrets.KUBECONFIG }}

      - name: Comment on PR with results
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ steps.tca.outputs.result-file }}
          
      - name: Optionally Fail if there are errors
        run: |
          if [ ${{ env.error-count }} -gt 0 ]; then
            exit 1
          fi
