name: Hybrid Config Analysis

on:
  pull_request:
    branches:
      - "main"

jobs:
  analyze-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Istio Configs
        id: tca
        uses: tetratelabs/tca-action@main
        continue-on-error: true
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }}
          #mesh-config: "./configs/gateway.yaml ./configs/virtualservice.yaml" # Multiple files with space separator
          # OR use newline separator
          mesh-config: |-
            test/manifest.yaml
            test/failed.yaml
          #   ./configs/gateway.yaml
          #   ./configs/virtualservice.yaml
          kube-config: ${{ secrets.KUBECONFIG }}
          #local-only: true
          
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ steps.tca.outputs.result-file }}

      - name: Optionally Fail if there are errors
        run: |
          if [ ${{ env.error-count }} -gt 0 ]; then
            exit 1
          fi
