name: Hybrid Config Analysis

on:
  pull_request:
    branches:
      - 'main'
    #paths:
    #  - '/gitops/**'

jobs:
  analyze-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Istio Configs
        uses: ajaymare/tca@main
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }}
          mesh-config: |-
            gitops/bookinfo/bookinfo-gateway.yaml
            gitops/bookinfo/bookinfo.yaml
          github-token: ${{ secrets.GH_PAT }}
          kube-config: ${{ secrets.KUBECONFIG }}

      - name: Comment on PR with results
        uses: thollander/actions-comment-pull-request@v3
        with:
          #file-path: ${{ steps.tca.outputs.result-file }}
          file-path: tca-output.txt
          mode: upsert
          create-if-not-exists: true
          github-token: ${{ secrets.GH_PAT }}
      - name: Optionally Fail if there are errors
        run: |
          if [ ${{ env.error-count }} -gt 0 ]; then
            exit 1
          fi
